### ISSUE TITLE
How can I use？

### ISSUE THREAD

**Issue by xunzh2000** [valzar-cbp/cbplus#1]

**Comment by valzar-cbp** [comment]
You just need some "Tampermonkey" addon for you browser.
Then copy and paste main (index.js) script and save :)

I will try to write some info about that in README :)

**Comment by valzar-cbp** [comment]
README.md updated.

**Comment by xunzh2000** [comment]
But I browse chaturbate website, there is no any change?thank you





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"valzar-cbp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 凌晨2:57
收件人:&nbsp;"valzar-cbp/cbplus"<cbplus@noreply.github.com&gt;;
抄送:&nbsp;"不戒"<67015683@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [valzar-cbp/cbplus] How can I use？ (#1)




README.md updated.
