### ISSUE TITLE
But I browse chaturbate website, there is no any change?

### ISSUE THREAD

**Issue by xunzh2000** [valzar-cbp/cbplus#2]
thank you

**Comment by valzar-cbp** [comment]
if you did everything right you won't see ads and there will be 1 special "gold" option in top menu "CBPLUS" which will take you to multiple cams player :) https://chaturbate.com/cams-cbplus/

![](https://i.postimg.cc/3xrTx6nH/1.png)
https://i.postimg.cc/v87kxh18/2.png

**Comment by xunzh2000** [comment]
Ok, thank you
